### ISSUE TITLE
How to add too many data

### ISSUE THREAD

**Issue by Shishir-K-Talukder** [amitkumardemo/Certificate-Generator-#1]
bro can you help me to add too much data input option
like date of birth, father name ,mother name

**Comment by amitkumardemo** [comment]
In Which section you want to add too much data please tell me clearly then I try to help you

**Comment by amitkumardemo** [comment]
#fix: #1 To add many data in the certificate or any pdf you change your js code add name you want to add then change js height , size accourding to you . 
![Screenshot 2024-11-04 180323](https://github.com/user-attachments/assets/0cf0ab71-18d1-40a6-ad33-b1cee3dc4fb3)
